version: '3'

services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        environment: 
            NODE_ENV: development
        command: ["yarn", "run", "test"]
        depends_on:
            - mongodb
    mongodb:
        image: circleci/mongo:3.5.13-jessie-ram
        volumes:
            - ./db:/data/db
        restart: always
