version: '3'

services:
    app:
        image: app
        build: 
            context: .
            dockerfile: Dockerfile
        environment: 
            NODE_ENV: development
        command: ["yarn", "run", "dev"]
        volumes:
            - ./app/:/usr/local/n-blog/app/
            - ./__tests__/:/usr/local/n-blog/__tests__/
        networks:
            back:
                ipv4_address: 172.16.238.10 
        ports:
            - 5000:5000
        depends_on:
            - mongodb
    mongodb:
        image: mongo:3.5.13-jessie
        volumes:
            - ./db:/data/db
        networks: 
            back:
                ipv4_address: 172.16.238.5
        ports:
            - 27017:27017
        restart: always
networks:
    back:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24