branch-defaults:
  master:
    environment: nblog
global:
  application_name: nblog
  branch: null
  default_ec2_keyname: nblog
  default_platform: Docker 17.06.2-ce
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
